config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :contacts
  root 'application#home'

  resources :posts do
    resources :comments, only: :create
  end

  get '/about' => 'application#about'
  get '/contact_me' => 'contacts#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :author, :presence => true
  validates :body, :presence => true
  belongs_to :post
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :presence => true
  validates :title, :uniqueness => true
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def about
  end

  def home
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])

    if @post.comments.create( comment_params )
      redirect_to @post, notice: "Comment created!"
    else
      redirect_to @post, alert: "Error"
    end
  end


  private

  def comment_params
    params.require( :comment ).permit( :author, :body, :email )
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :message)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def friendly_date(d)
    d.strftime("%B %e, %Y") # input (year, month, day) outputs month day, year
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/about.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <div class="page-heading">
        <h1>Gary Marx</h1>
        <span class="subheading">Dedicated, fun, & looking to improve life.</span>
      </div>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-lg-8 col-md-10 mx-auto">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
    </div>
  </div>
</div>

<hr>

app/views/application/home.html.erb
<main role="main">
  <div class="card bg-dark text-white">
    <%= image_tag('nstar.jpg', height: "450", class: "card-img overflow-hidden") %>
    <!-- <img class="card-img" src="..." alt="Card image"> -->
    <div class="card-img-overlay">
      <h1 class="display-3 text-center top">Hello, Hipcamp!</h1>
      <p class="text-center">This is a simple rails site built for us to work through.</p>
    </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-4">
        <h2>Keep Up To Date</h2>
        <div class="text-center"><%= link_to 'Blog »', posts_path, class: "btn btn-primary" %></div>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo. </p>
        <div><a class="btn btn-secondary" href="#" role="button">View details »</a></div>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
        <div><a class="btn btn-secondary" href="#" role="button">View details »</a></div>
      </div>
    </div>

    <hr>

  </div> <!-- /container -->

</main>

app/views/comments/_comment.html.erb
<p><%= comment.author %> says:</p>

<blockquote>
  <%= comment.body %>
</blockquote>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group w-50 float-left">
    <div class="form-group floating-label-form-group controls field">
      <% form.label :name %>
      <%= form.text_field :name, id: :contact_name, class: "form-control w", placeholder: "Keanu Reeves" %>
      <p class="help-block text-danger"></p>
    </div>
  </div>

  <div class="control-group w-50 float-left">
    <div class="form-group floating-label-form-group controls field">
      <% form.label :email %>
      <%= form.text_field :email, id: :contact_email, class: "form-control", placeholder: "Keanu@johnwick3.com" %>
      <p class="help-block text-danger"></p>
    </div>
  </div>

  <div class="control-group w-50 float-left">
    <div class="form-group col-xs-12 floating-label-form-group controls">
      <% form.label :phone %>
      <%= form.number_field :phone, id: :contact_phone, class: "form-control", type: "tel", placeholder: "(415) 867-5309" %>
      <p class="help-block text-danger"></p>
    </div>
  </div>
  <div class="control-group">
    <div class="form-group floating-label-form-group controls">
      <%= form.label :message %>
      <%= form.text_area :message, id: :contact_message, class: "form-control", placeholder: "Tell me what you want", rows: "5"  %>
      <p class="help-block text-danger"></p>
    </div>
  </div>

  <div class="actions">
    <br>
  <div id="success"></div>
  <div class="form-group actions">
    <%= form.submit class: "btn btn-primary", id:"sendMessageButton" %>
  </div>

  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path, class: "btn btn-primary" %>

app/views/contacts/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <div class="page-heading">
        <h1>Contact Me</h1>
        <span class="subheading">Have questions? Get answers.</span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">

      <%= render 'form', contact: @contact %>

    </div>
  </div>
</div>


<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Blog</title>

    <!-- Custom fonts for this template -->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <%= link_to 'Le Blog', root_path, class: "navbar-brand" %>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to 'About', about_path, class: "navbar-brand" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Contact', contact_me_path, class: "navbar-brand" %>
            </li>

            <li class="nav-item">
              <p class="navbar-text float-right">
              <% if user_signed_in? %>
                Logged in as <strong><%= current_user.email %></strong>.
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
                <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
              <% end %>
              </p>
            </li>

          </ul>
        </div>
      </div>
    </nav>

    <% if notice %>
      <div class="container">
        <div class="row">
          <p class="alert alert-success"><%= notice %></p>
        </div>
    <% end %>
    <% if alert %>
      <div class="container">
        <div class="row">
          <p class="alert alert-danger"><%= alert %></p>
        </div>
      </div>
    <% end %>

    <%= yield %>
  </body>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack">
                  <i class="fa fa-camera-retro"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack">
                  <i class="fa fa-twitter fa-stack-1x"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack">
                  <i class="fa fa-facebook"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack">
                  <i class="fa fa-github"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; GM 2019</p>
        </div>
      </div>
    </div>
  </footer>
</html>

app/views/posts/_form.html.erb
<div class="row">

  <%= form_with(model: post, local: true) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
</div>

<div class="row">

  <div class="field col-6">
  <%= form.label :title %>
  <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field col-6">
    <%= form.label :author %>
    <%= form.text_field :author, id: :author %>
  </div>
</div>
<div class="row">

  <div class="field col-12">
    <%# form.label :body %>
    <%= form.text_area :body, id: :post_body, placeholder: "Write for the blog!", rows: 5, class: "w-100" %>
  </div>

    <div class="actions col-12 text-center">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container mt-5">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <div class="page-heading">
        <h1>My Posts</h1>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">

        <% @posts.each do |post| %>
          <div class="clearfix mt-3">
              <h3 class=""><%= link_to post.title, post %></h3>
              <div class="col-med-4 float-left"><i><%= friendly_date post.created_at %></i></div>
              <!-- <p><%# post.body %></p> -->
              <div class="col-med-6 float-right">
                <%= link_to 'Edit', edit_post_path(post), class: "btn-outline-secondary btn-sm", type: "button" %>
                <%= link_to 'Destroy', post, method: :delete, data: { confirm: "Delete this post?" }, class: "btn-outline-danger btn-sm", type: "button" %>
              </div>
              <p class="">
          </div>
        <% end %>
        <%= link_to 'New Post', new_post_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>

<br>

app/views/posts/new.html.erb
<div class="container top">
  <div class="row">
    <h1>New Post</h1>
  </div>

    <%= render 'form', post: @post %>

  <div class="row">
    <%= link_to 'Back', posts_path, class: 'btn btn-outline-secondary btn-sm' %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container text-center mt-7">

  <h2><%= @post.title %></h2>
  <div>
    <p><%= @post.body %></p>
  </div>

  <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-sm" %> |
  <%= link_to 'Back', posts_path, class: "btn btn-sm" %>

  <h3>Comments</h3>
  <%= render @post.comments %>
</div>